First homework
umearesn/Homeworks pull request #1
Opened 2018-10-23 10:43 UTC by umearesn

2018-10-23 18:34 UTC, saint88 requested changes
Нужно исправить замечания в коде и написать остальные задачки, пока написано всего 5 задачек и последняя 6 задачка не доконца.

2018-10-23 18:34 UTC, saint88 commented on src/main/java/JavaPractice8/task_6/Filter.java
> +        /*Map depts = new HashMap<String, Integer>();
А что это за комментированный код? Такого кода быть не должно. Надо убрать.

2018-10-23 18:34 UTC, saint88 commented on src/main/java/JavaPractice8/task_6/Filter.java
> +        f.getPopularDept(lst);
А где вывод 3 популярных факультетов?

2018-10-23 18:34 UTC, saint88 commented on src/main/java/JavaPractice8/task_6/StudentsComparator.java
> +public class StudentsComparator implements Comparator<Student> {
Вот этот весь код можно было написать в виде одной лямбды (Student a, Student b) -> a.getName().compareToIgnoreCase(b.getName()) и прямо в фильтре стрима. Надо этот компаратор сделать в виде лямбды.

2018-10-23 19:51 UTC, umearesn commented on src/main/java/JavaPractice8/task_6/Filter.java
> +        f.getPopularDept(lst);
К сожалению, я не очень понял, как это сделать с помощью StreamAPI. Или это без него и делается?

2018-10-24 06:42 UTC, saint88 requested changes

2018-10-24 06:42 UTC, saint88 commented on src/main/java/JavaPractice8/task_6/Filter.java
> +        f.getPopularDept(lst);
Неее можно сделать через стримы. Смотри у тебя есть студенты и факультеты. Наша первая задача просто посчитать количество каждого факультета. Но если ты просто посчитаешь факультеты, то будет непонятно какой факультет сколько повторяется в списке, поэтому нам необходимо это как-то связать и тут нам на помощь приходят мапы. В нашей мапе ключом будет факультет, а значением количество повторений этого факультета. Потом в стриме мы эту мапу сортируем по значениям и получаем топ 3. Но ты же помнишь, что у мапы есть Entry (первая лекция), который содержит, ключ и значение (мы с тобой после первой лекции знаем что в мапе хранятся именно Entry). Так давай отсортируем нашу мапу по значению ентри, возьмем лимит 3 (нам же нужен топ 3) и выведем у полученного стрима этих Entry ключи (наши факультеты). И все. Задачка решена.

Вот пример кода:

Map<String, Integer> topMap = new HashMap<>();
        students
                .forEach(
                        student ->
                            topMap.put(
                                    student.getDepartament(),
                                    topMap.containsKey(student.getDepartament()) ?
                                            topMap.get(student.getDepartament()) + 1
                                            : 1
                                    )
                );

        topMap.entrySet().stream()
                .sorted(Map.Entry.comparingByValue(Comparator.reverseOrder()))
                .limit(3)
                .forEach(entry -> System.out.println(entry.getKey()));

2018-10-24 11:18 UTC, umearesn commented on src/main/java/JavaPractice8/task_6/Filter.java
> +        f.getPopularDept(lst);
Интересно, спасибо. Я пытался через map, там именно этот кусок и закомментирован) Но вот со стримом не придумал, сейчас переделаю

2018-10-24 19:10 UTC, closed without merging