Homework3
umearesn/Homeworks pull request #6
Opened 2018-11-20 13:11 UTC by umearesn

Добрый день, Павел. Посмотрите, пожалуйста, первое задание из третьей домашки. Я бы хотел исправить замечания. если будут. Другие доотправлю позднее, хочу ориентироваться на первое.

2018-11-20 13:40 UTC, saint88 requested changes
В целом неплохо. Но нужно немного подправить замечания

2018-11-20 13:40 UTC, saint88 commented on pom.xml
> +            <scope>test</scope>
Скоп тут надо убрать

2018-11-20 13:40 UTC, saint88 commented on src/main/java/JUnitHamcrestMockitoHomework/test/java/task_1/NegativeUnitTests/NegativeTest1.java
> +import junit.framework.TestCase;
org.junit.Assert

2018-11-20 13:40 UTC, saint88 commented on src/main/java/JUnitHamcrestMockitoHomework/test/java/task_1/NegativeUnitTests/NegativeTest1.java
> +        TestCase.assertEquals("Массив не содержит лишних чисел", expected, actual);
Используй статический импорт, чтобы использовать assertEquals()

2018-11-20 13:40 UTC, saint88 commented on src/main/java/JUnitHamcrestMockitoHomework/test/java/task_1/NegativeUnitTests/NegativeTest2.java
> +    public void test_positive2(){
Такой же тест написан выше, только другие данные и он позитивный, а не негативный. Негативный тест - тест с данными, которые не ожидаются и не являются для системы валидными, например null или пустой список.

2018-11-20 13:40 UTC, saint88 commented on src/main/java/JUnitHamcrestMockitoHomework/test/java/task_1/NegativeUnitTests/NegativeTest1.java
> +    public void test_positive1(){
В сьюте с негативными тестами лежит позитивный тест

2018-11-20 13:40 UTC, saint88 commented on src/main/java/JUnitHamcrestMockitoHomework/test/java/task_1/NegativeUnitTests/NegativeTest2.java
> +    public void test_positive2(){
В одном сьюте должны быть все тесты, например в этом негативном сьюте должны быть тестовые негативные методы, а не 1 тест на один сьют

2018-11-20 13:40 UTC, saint88 commented on src/main/java/JUnitHamcrestMockitoHomework/test/java/task_1/NegativeUnitTests/NegativeTestSuite.java
> +        NegativeTest1.class,
Зачем объединять 2 тест сьюта с одинаковым типом тестов. Они же оба отрицательные

2018-11-20 13:40 UTC, saint88 commented on src/main/java/JUnitHamcrestMockitoHomework/test/java/task_1/PositiveUnitTests/PositiveTest2.java
> +
По поводу сьютов написал выше. Нужно сделать все положительные тесты в одном сьюте (классе)

2018-11-20 13:40 UTC, saint88 commented on src/main/java/JUnitHamcrestMockitoHomework/test/java/task_1/PositiveUnitTests/PositiveTestSuite.java
> +@Suite.SuiteClasses({
Аналогично как написано выше. Не нужно так объединять, тем более в задании написано, что нужно тесты разделить по положительным и отрицательным. По классам имеет смысл разделить только тогда, когда у тебя тесты проверяют например разные классы

2018-11-20 14:10 UTC, umearesn commented
Я правильно понимаю, что правильнее будет сделать всего 2 сьюта (2 класса, иными словами), в одном из которых будут все позитивные тесты, а в другом - все негативные? То есть я не делаю по классу на тест

2018-11-21 10:09 UTC, umearesn commented on src/main/java/JUnitHamcrestMockitoHomework/test/java/task_1/NegativeUnitTests/NegativeTest2.java
> +    public void test_positive2(){
![default](https://user-images.githubusercontent.com/36409760/48834354-a8ec5680-ed8e-11e8-842b-9133f38ab586.png)
То есть позитивнй тест кейс выглядит так? И аналогичный один класс для негативных?

2018-11-27 06:39 UTC, saint88 requested changes
Тесты ничего не тестируют. Нужно это исправить

2018-11-27 06:39 UTC, saint88 commented on src/main/java/JUnitHamcrestMockitoHomework/main/java/task_1/PrimeNumbers.java
> +    private static int correctInput(){
Почему метод static?

2018-11-27 06:39 UTC, saint88 commented on src/main/java/JUnitHamcrestMockitoHomework/main/java/task_1/PrimeNumbers.java
> +        Scanner in = new Scanner(System.in);
Ввод чисел по сути тут не нужен. Задача этого класса выводить определенные числа: простые, например только натуральные и т.д. А вот ввод чисел и передачу его методам этого класса имеет смысл оформить в другом классе, который будет отвечать за ввод данных и т.д. Поэтому тут делаешь только один метод, который тебе вернет массив простых чисел и все.

2018-11-27 06:39 UTC, saint88 commented on src/main/java/JUnitHamcrestMockitoHomework/main/java/task_1/PrimeNumbers.java
> +        Scanner in = new Scanner(System.in);
Этот метод надо убрать . в дальнейшем не забывать об абстрагировании

2018-11-27 06:39 UTC, saint88 commented on src/main/java/JUnitHamcrestMockitoHomework/main/java/task_1/PrimeNumbers.java
> +        Scanner in = new Scanner(System.in);
И оформи метод получения простых чисел ввиде отдельного класса и не нужно все пихать в несчастный один класс с main

2018-11-27 06:39 UTC, saint88 commented on src/main/java/JUnitHamcrestMockitoHomework/main/java/task_1/PrimeNumbers.java
> +    public static ArrayList<Integer> filterNumbers(){
Почему статик и в задаче сказано о массиве, а не списке =)

2018-11-27 06:39 UTC, saint88 commented on src/main/java/JUnitHamcrestMockitoHomework/main/java/task_1/PrimeNumbers.java
> +        int n = correctInput();
Тут нужно N получать в методе, а не из System.in

2018-11-27 06:39 UTC, saint88 commented on src/main/java/JUnitHamcrestMockitoHomework/main/java/task_1/PrimeNumbers.java
> +        int n = correctInput();
И этот метод должен быть в отдельном классе (абстрагирование)

2018-11-27 06:39 UTC, saint88 commented on src/main/java/JUnitHamcrestMockitoHomework/main/java/task_1/PrimeNumbers.java
>          for (Integer i: input) {
А зачем выносить в отдельный метод вывод в консоль? Вот тут логичнее сделать его в main

2018-11-27 06:39 UTC, saint88 commented on src/main/java/JUnitHamcrestMockitoHomework/main/java/task_2/ComparatorBySums.java
> +public class ComparatorBySums implements Comparator<ArrayList<Integer>> {
А зачем ты держишь закомментированый компаратор? Если он не нужен, то удаляй или не нужно его комитить и пушить в ветку

2018-11-27 06:39 UTC, saint88 commented on src/main/java/JUnitHamcrestMockitoHomework/main/java/task_2/Matrix.java
> +    private Integer correctInput(){
Я бы ввод матрицы не держал в классе, который отвечает за обработку матрицы. Наверное логичнее этот код убрать и вынести в другой класс или вообще в main

2018-11-27 06:39 UTC, saint88 commented on src/main/java/JUnitHamcrestMockitoHomework/main/java/task_2/Matrix.java
> +    public void initMatrix(){
Аналогично как написано выше

2018-11-27 06:39 UTC, saint88 commented on src/main/java/JUnitHamcrestMockitoHomework/main/java/task_2/Matrix.java
> +    public void printMatrix(){
Вывод матрицы тоже логичнее убрать из этого класса, так как основная задача этого класса - обработка матрицы

2018-11-27 06:39 UTC, saint88 commented on src/main/java/JUnitHamcrestMockitoHomework/main/java/task_2/Matrix.java
> +    public static <K, V> void printMap(Map<K, V> map) {
Аналогично выше

2018-11-27 06:39 UTC, saint88 commented on src/main/java/JUnitHamcrestMockitoHomework/main/java/task_2/Matrix.java
> +    public void sortTheRows(){
Этот метод должен получать на входе матрицу и возвращать уже ее отсортированную. Так как задача этого метода в классе - обработать матрицу, которая приходит на вход

2018-11-27 06:39 UTC, saint88 commented on src/main/java/JUnitHamcrestMockitoHomework/main/java/task_2/Matrix.java
> +        this.matrix = res.matrix;
Этот метод не должен выводить матрицу, а должен вернуть отсортированную матрицу

2018-11-27 06:39 UTC, saint88 commented on src/main/java/JUnitHamcrestMockitoHomework/main/java/task_2/Matrix.java
> +    public static void main(String[] args) {
А что тут делает метод main? Этот же класс отвечает за обработку матрицы. В общем метод main надо убрать

2018-11-27 06:39 UTC, saint88 commented on src/main/java/JUnitHamcrestMockitoHomework/test/java/task_1/PositiveUnitTests/PositiveTestSuite.java
> +    public void test_positive1(){
Надо нормально назвать методы тестов. Что это за test1 и test2? Например назови sort_empty_matrix. Так же намного понятнее

2018-11-27 06:39 UTC, saint88 commented on src/main/java/JUnitHamcrestMockitoHomework/test/java/task_1/PositiveUnitTests/PositiveTestSuite.java
>  public class PositiveTestSuite {
А что эти тесты кстати тестируют? Метод add интерфейса Collection? Так сразу скажу без тестирования, работают они хорошо. Их уже в оракле потестировали за нас. =)
Где вызов методов тестируемого класса?

2018-11-27 12:56 UTC, umearesn commented
Переделал еще раз первое задание. Немного не понимаю, что делать с негативными тестами. Если отдавать в метод не int - ошибка компиляции, и тогда даже исключение ловить не приходится.

2018-11-28 09:15 UTC, saint88 requested changes
Написал еще немного комментариев

2018-11-28 09:15 UTC, saint88 commented on src/main/java/JUnitHamcrestMockitoHomework/main/java/task_1/PrimeNumbers.java
>          for (Integer i: input) {
Так и не исправил вывод в консоль

2018-11-28 09:15 UTC, saint88 commented on src/main/java/JUnitHamcrestMockitoHomework/main/java/task_1/PrimeNumbers.java
>      public static void main(String[] args) {
Зачем тут метод main? Задача этого класса возвращать определенные наборы чисел, в данном случае массив простых чисел

2018-11-28 09:15 UTC, saint88 commented on src/main/java/JUnitHamcrestMockitoHomework/main/java/task_1/PrimeNumbers.java
>      public static void main(String[] args) {
Зачем тут main?

2018-11-28 09:15 UTC, saint88 commented on src/main/java/JUnitHamcrestMockitoHomework/test/java/task_1/NegativeUnitTests/NegativeTestSuite.java
> +    public void test_negative1(){
Негативный кейс - это кейс с данными, которые являются не совсем нормальными и ожидаемыми в системе. Например первый негативный тест это передача null. Соответственно и назови его как null_number_test()

2018-11-28 09:15 UTC, saint88 commented on src/main/java/JUnitHamcrestMockitoHomework/test/java/task_1/NegativeUnitTests/NegativeTestSuite.java
> +    public void test_negative2(){
Второй можно оставить как передачу отрицательной границы чисел.

2018-11-28 09:15 UTC, saint88 commented on src/main/java/JUnitHamcrestMockitoHomework/test/java/task_1/NegativeUnitTests/NegativeTestSuite.java
> +    public void test_negative2(){
Только назови его по человечески, а так вполне нормально. Т.е. мы смотрим реакцию системы на отрицательное значение границы

2018-11-28 09:15 UTC, saint88 commented on src/main/java/JUnitHamcrestMockitoHomework/test/java/task_1/PositiveUnitTests/PositiveTestSuite.java
> +        Integer[] actual = prime.filterNumbers(5);
Этот тест одинаковый с передачей 2. И еще почему у тебя в этом тесте 1 не простое число, в тесте чуть выше 1 в ожидаемом результате - простое число.

2018-12-05 08:27 UTC, saint88 approved these changes
Отлично

2018-12-05 08:28 UTC, saint88 commented
У тебя конфликт в pom.xml. Надо исправить и тогда дз будет влито в мастер и принято.

2018-12-06 06:09 UTC, merged